name:                GhcCore
version:             0.1.0.0
github:              "githubuser/GhcCore"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/GhcCore#readme>

dependencies:
  - base ^>= 4.15
  - ghc ^>= 8.10.7

# ghc-options:
# - -Wall
# - -Wcompat
# - -Widentities
# - -Wincomplete-record-updates
# - -Wincomplete-uni-patterns
# - -Wmissing-export-lists
# - -Wmissing-home-modules
# - -Wpartial-fields
# - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:     CoreDump.Plugin


# executables:
#   GhcCore-exe:
#     main:                Main.hs
#     source-dirs:        /workspaces/GhcCore/app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     #- -DGHC_LOADED_INTO_GHCI
#   dependencies:
#     - base
#     - ghc
#     - ghc-boot
#     - dhall
#     - text


# base      >= 4.5 && <4.10
#     , mtl       >= 2.2 && <2.3
#     , time      >= 1.3 && <1.6
#     , ghc       >= 7.8 && <= 8.0.1
#     , ghc-paths >= 0.1 && <0.2
#     , haskeline >= 0.7 && <0.8

# tests:
#   GhcCore-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - GhcCore


